CREATE TABLE [dbo].[PreReservationProspect]
(
[id] [bigint] NOT NULL IDENTITY(1, 1),
[idformule] [bigint] NULL,
[datesouhaitee1] [datetime] NULL,
[datesouhaitee2] [datetime] NULL,
[datesouhaitee3] [datetime] NULL,
[heure1] [nvarchar] (50) COLLATE French_CI_AS NULL,
[heure2] [nvarchar] (50) COLLATE French_CI_AS NULL,
[heure3] [nvarchar] (50) COLLATE French_CI_AS NULL,
[dateaction] [datetime] NULL,
[valide] [bit] NULL,
[status] [int] NULL,
[idprospect] [bigint] NULL,
[dateaction2] [datetime] NULL,
[daterelance] [datetime] NULL,
[dateReponsePresta] [datetime] NULL,
[reponsePresta] [int] NULL,
[iduser] [bigint] NULL,
[idclient] [bigint] NULL,
[cadeau] [bit] NULL,
[occasion] [bigint] NULL,
[civ] [int] NULL,
[othPerson] [int] NULL,
[d1ok] [bit] NULL,
[d2ok] [bit] NULL,
[d3ok] [bit] NULL,
[datecommande] [datetime] NULL,
[idusercommande] [bigint] NULL,
[heureproposee] [nvarchar] (10) COLLATE French_CI_AS NULL,
[dateppr1] [datetime] NULL,
[dateppr2] [datetime] NULL,
[dateppr3] [datetime] NULL,
[heureppr1] [nvarchar] (50) COLLATE French_CI_AS NULL,
[heureppr2] [nvarchar] (50) COLLATE French_CI_AS NULL,
[heureppr3] [nvarchar] (50) COLLATE French_CI_AS NULL,
[datepropositionprestataire] [datetime] NULL,
[datepropositionprestatairereponse] [datetime] NULL,
[remarqueproposition] [nvarchar] (max) COLLATE French_CI_AS NULL,
[prestaNoDispDate] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
