CREATE TABLE [dbo].[Voucher]
(
[id] [bigint] NOT NULL IDENTITY(1, 1),
[idLigneCommande] [bigint] NULL,
[idFormule] [bigint] NOT NULL,
[datePrestaSouhaitee] [datetime] NULL,
[datePrestaConfirmee] [datetime] NULL,
[datePrestaRealisee] [datetime] NULL,
[dateAchat] [datetime] NOT NULL,
[dateFinValidite] [datetime] NULL,
[idClient] [bigint] NOT NULL,
[commentaire] [text] COLLATE French_CI_AS NULL,
[valide] [bit] NOT NULL,
[causeInvalidite] [nvarchar] (255) COLLATE French_CI_AS NULL,
[prenom] [nvarchar] (30) COLLATE French_CI_AS NOT NULL,
[nom] [nvarchar] (50) COLLATE French_CI_AS NOT NULL,
[mobile] [nvarchar] (20) COLLATE French_CI_AS NOT NULL,
[email] [nvarchar] (255) COLLATE French_CI_AS NOT NULL,
[dateEnvoiEmail] [datetime] NULL,
[idPassport] [bigint] NULL,
[idControleVoucher] [bigint] NULL,
[libelle] [nvarchar] (255) COLLATE French_CI_AS NULL,
[cp] [nvarchar] (50) COLLATE French_CI_AS NULL,
[ville] [nvarchar] (255) COLLATE French_CI_AS NULL,
[enregistrer] [bit] NULL CONSTRAINT [DF_Voucher_enregistrer] DEFAULT ((0)),
[heurePresta] [nvarchar] (50) COLLATE French_CI_AS NULL,
[ecart] [decimal] (18, 2) NULL,
[commentairepresta] [text] COLLATE French_CI_AS NULL,
[ajout] [bit] NULL,
[tvaAjust] [decimal] (18, 2) NULL,
[d1] [datetime] NULL,
[d2] [datetime] NULL,
[d3] [datetime] NULL,
[nbps] [int] NULL,
[htajustcv] [decimal] (18, 2) NULL,
[comajustcv] [decimal] (18, 2) NULL,
[dateLettreAnnulation] [datetime] NULL,
[cadeau] [bit] NULL,
[occasion] [bigint] NULL,
[civ] [int] NULL,
[othPerson] [int] NULL,
[prolongee] [bit] NULL,
[dateprolongation] [datetime] NULL,
[cv_tauxcommission] [decimal] (18, 9) NULL,
[cv_prixpublic] [decimal] (18, 3) NULL,
[poids] [int] NULL,
[dateChangementActivite] [datetime] NULL,
[idremisechangement] [bigint] NULL,
[idemploye2] [bigint] NULL,
[dateAnnulationChangement] [datetime] NULL,
[prestaNoDispDate] [datetime] NULL,
[dpFrom] [datetime] NULL,
[dpTo] [datetime] NULL,
[autoTour] [int] NULL,
[dateett] [datetime] NULL,
[userett] [bigint] NULL,
[arretPartenariat] [datetime] NULL,
[albatros] [bit] NULL,
[cv_prixpublic2] [decimal] (18, 3) NULL,
[cv_tauxcommission2] [decimal] (18, 9) NULL,
[tvaAjust2] [decimal] (18, 2) NULL,
[htajustcv2] [decimal] (18, 2) NULL,
[comajustcv2] [decimal] (18, 2) NULL,
[idcontrolevoucher2] [bigint] NULL,
[dpHeure] [nvarchar] (50) COLLATE French_CI_AS NULL,
[voucherRemp] [bigint] NULL,
[voucherParent] [bigint] NULL,
[freePro] [bit] NULL,
[dateEnregistrement] [datetime] NULL,
[prestaEnregistrement] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Voucher] ADD CONSTRAINT [PK_Voucher] PRIMARY KEY CLUSTERED  ([id]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Voucher] ADD CONSTRAINT [FK_Voucher_Client] FOREIGN KEY ([idClient]) REFERENCES [dbo].[Client] ([id])
GO
ALTER TABLE [dbo].[Voucher] ADD CONSTRAINT [FK_Voucher_Formule] FOREIGN KEY ([idFormule]) REFERENCES [dbo].[Formule] ([id])
GO
ALTER TABLE [dbo].[Voucher] ADD CONSTRAINT [FK_Voucher_LigneCommande] FOREIGN KEY ([idLigneCommande]) REFERENCES [dbo].[LigneCommande] ([id])
GO
