CREATE TABLE [dbo].[Prestataire]
(
[id] [bigint] NOT NULL IDENTITY(1, 1),
[societe] [nvarchar] (100) COLLATE French_CI_AS NOT NULL,
[adresse] [nvarchar] (255) COLLATE French_CI_AS NOT NULL,
[codePostal] [nvarchar] (20) COLLATE French_CI_AS NOT NULL,
[ville] [nvarchar] (100) COLLATE French_CI_AS NOT NULL,
[nomGerant] [nvarchar] (100) COLLATE French_CI_AS NOT NULL,
[remarques] [text] COLLATE French_CI_AS NULL,
[valide] [bit] NOT NULL CONSTRAINT [DF_Prestataire_valide] DEFAULT ((0)),
[login] [nvarchar] (100) COLLATE French_CI_AS NOT NULL,
[mdp] [nvarchar] (100) COLLATE French_CI_AS NOT NULL,
[compteComptable] [nvarchar] (20) COLLATE French_CI_AS NOT NULL,
[specialEnvoiEmailNonDate] [bit] NOT NULL,
[rib] [nvarchar] (30) COLLATE French_CI_AS NOT NULL,
[cdp] [nvarchar] (30) COLLATE French_CI_AS NOT NULL,
[portFrance] [decimal] (18, 2) NOT NULL,
[portCEE] [decimal] (18, 2) NOT NULL,
[visuVoucherEnAttente] [bit] NOT NULL,
[specialEnvoiEmail] [bit] NULL,
[idcompta] [nvarchar] (50) COLLATE French_CI_AS NULL,
[resaclientpresta] [bit] NULL,
[resaautopresta] [bit] NULL,
[resadelai] [int] NULL,
[resadelaitype] [int] NULL,
[motif] [bigint] NULL,
[centre] [nvarchar] (max) COLLATE French_CI_AS NULL,
[prestaAcontacter] [int] NULL,
[prestaAcontacterMotif] [nvarchar] (max) COLLATE French_CI_AS NULL,
[prestaAcontacterMotifId] [int] NULL,
[heureRDVId] [int] NULL,
[heureRDVMotif] [nvarchar] (max) COLLATE French_CI_AS NULL,
[agentbic] [nvarchar] (max) COLLATE French_CI_AS NULL,
[iban] [nvarchar] (max) COLLATE French_CI_AS NULL,
[raisonsociale] [nvarchar] (max) COLLATE French_CI_AS NULL,
[infojour] [nvarchar] (max) COLLATE French_CI_AS NULL,
[hotel] [bit] NULL,
[infocv] [text] COLLATE French_CI_AS NULL,
[dateMailDispo] [datetime] NULL,
[cvmix] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Prestataire] ADD CONSTRAINT [PK_Prestataire] PRIMARY KEY CLUSTERED  ([id]) ON [PRIMARY]
GO
